// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehuyoichpzyxzlwhfzxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVodXlvaWNocHp5eHpsd2hmenhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNTc3MzAsImV4cCI6MjA3MzgzMzczMH0.ecq99trVsg75GcdbFqyoo74YCvw76xk2RZHvr2JSXsQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});